server:
  port: 8081


spring:
  datasource:
    username: root
    password: '050596'
    url: jdbc:mysql://localhost:3306/my-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml




logging:
  config: classpath:logback-spring.xml
  file:
    path: /var/log/service.log

